default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user_name: bfp
  password: password

development:
  <<: *default
  database: bfp-dev

test:
  <<: *default
  database: bfp-test

production:
  <<: *default
  database: bfp
